### ISSUE TITLE
Glimmer DSL for LibUI for Ruby Graphical User Interface

### ISSUE THREAD

**Issue by AndyObtiva** [dvarrui/proyectos-de-ejemplo#28]
Hi,

I noticed you've used libui in the past.

I'd like to note that libui is not meant to be used directly. It is a low-level Ruby C binding that requires C-style code with extra setup and memory management to function properly. The libui project page recommends Glimmer DSL for LibUI to write Ruby-style code instead. It offers a very friendly GUI DSL that is object-oriented and hierarchical (similar to how HTML works, but in pure Ruby). Glimmer is currently the most advanced Ruby desktop GUI library because it has bidirectional data-binding support, not found in competing libraries, so it enables writing very clean code.

You may learn more about the project over here:

https://github.com/AndyObtiva/glimmer-dsl-libui

The project includes many examples:

https://github.com/AndyObtiva/glimmer-dsl-libui#examples

Also, I blog about the project over here:

https://andymaleh.blogspot.com/search/label/LibUI

And, over here:

https://dev.to/t/libui

Last but not least, you can check out other Glimmer DSLs like:
- https://github.com/AndyObtiva/glimmer-dsl-gtk
- https://github.com/AndyObtiva/glimmer-dsl-swt (enables you to package Ruby apps as native Mac APP/DMG/PKG, Windows EXE/MSI, and Linux DEB/RPM files)
- https://github.com/AndyObtiva/glimmer-dsl-tk
- https://github.com/AndyObtiva/glimmer-dsl-swing
- https://github.com/AndyObtiva/glimmer-dsl-jfx
- https://github.com/AndyObtiva/glimmer-dsl-fx

By the way, I noticed you also mentioned the Gladiator Editor, which I've actually built for myself in Ruby using JRuby and [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt). Thank you!

Cheers!

p.s. you can close this issue right away. I only created to share information with you.

**Comment by dvarrui** [comment]
Thanks!
